### ISSUE TITLE
Class 'IP2City' not found

### ISSUE THREAD

**Issue by lovecn** [mylukin/ip2city#1]
`php artisan vendor:publish --provider="MyLukin\IP2City\ServiceProvider"`创建ip2city.php显示Nothing to publish
所以调用`var_dump(IP2City::ip2addr('115.28.212.163'));`的时候`Class 'IP2City' not found`

**Comment by mylukin** [comment]
是按照前面的顺序操作的每一步吗？

**Comment by mylukin** [comment]
php artisan vendor:publish --provider="MyLukin\IP2City\ServiceProvider"
Copied File [/vendor/mylukin/ip2city/src/config.php] To [/config/ip2city.php]
Publishing Complete!

**Comment by mylukin** [comment]
请按照文档上的每一步操作，不要出错。
